/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PresentationControls } from '@react-three/drei'
import { useFrame, Clock } from '@react-three/fiber'

export default function Model({ ...props }) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/laptop.glb')

    useFrame(({ clock }) => {
        group.current.rotation.y = clock.getElapsedTime() * 0.3
    })

    return (
        <group ref={group} {...props} dispose={null}>
            <PresentationControls
                snap={true}
                global={true}
                cursor={true}
                touch-action="none"
            >
                <mesh
                    geometry={nodes.Laptop_VOX001.geometry}
                    material={materials.palette}
                    position={[-0.17, -1.33, 0.08]}
                    rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                    geometry={nodes.Plane.geometry}
                    material={materials['Material.001']}
                    position={[-1.96, -1.33, -1.88]}
                    scale={[3.6, 1.09, 3.35]}
                />
            </PresentationControls>
        </group>
    )
}

useGLTF.preload('/laptop.glb')
